#!/usr/bin/bash

#
# CC BY-NC-SA 4.0 Deed 
# k_menu, a work by clyde
#

# example usage: 
# $ bash k_menu "rofi -dmenu"
# $ bash k_menu dmenu

menu=$1
test -z $1 && exit 1

main_menu=$(echo -e "continue" | $menu -p "careful: this will display your logins! select any to continue" -lines 0)

test -z $kdatabase && {
	echo -e "\033[90mdefaulting to kdatabase=\$HOME/cornflakes\033[0m"
	kdatabase=$HOME/cornflakes
}

kdatabaseid="$(echo $kdatabase | b2sum | cut -b1-6)$(basename $kdatabase)"

if test ! -e /dev/mapper/$kdatabaseid; then
    st -e k open || { 
        k close
        exit 1
    }
fi

array1=($(k list_menu | awk -F $'\t' '{print $1}'))
logins=($(k list_menu | awk -F $'\t' '{print $2}'))

entry=$(k list_menu | awk -F $'\t' '{print $1" "$2}' | nl -s '. ' -w 1 | sed 1d 2>/dev/null | $menu | awk -F '.' '{print $1}') || exit 1
password=$(k get $entry | awk -F $'\t' '{print $1}'| tail -n1)
login=$(${words[$entry]})
# totp=$(k totp $entry)

choice=$(echo -e "login+password\npassword\nlogin\ntotp\nlogin[enter]password" | $menu) || exit 1

{
case $choice in
    "login+password")
        for (( i=0; i<${#login}; i++ )); do
            char="${login:$i:1}"
            xdotool type "$char"
        done
        sleep 0.05
        xdotool key Tab
        sleep 0.05
        for (( i=0; i<${#password}; i++ )); do
            char="${password:$i:1}"
            xdotool type "$char"
        done
        ;;
    "login[enter]password")
        for (( i=0; i<${#login}; i++ )); do
            char="${login:$i:1}"
            xdotool type "$char"
        done
        sleep 0.05
        xdotool key Enter
        sleep 1.1
        for (( i=0; i<${#password}; i++ )); do
            char="${password:$i:1}"
            xdotool type "$char"
        done
        ;;
    "password")
        for (( i=0; i<${#password}; i++ )); do
            char="${password:$i:1}"
            xdotool type "$char"
        done
        ;;
    "login")
        for (( i=0; i<${#login}; i++ )); do
            char="${login:$i:1}"
            xdotool type "$char"
        done
        ;;
    "totp")
        for (( i=0; i<${#totp}; i++ )); do
            char="${totp:$i:1}"
            xdotool type "$char"
        done
        ;;
esac

notify-send "done typing, you may press enter"

} &


