#!/usr/bin/bash

#
# CC BY-NC-SA 4.0 Deed 
# kmenu for k password manager, a work by clyde
#

# example usage: 
#
# for rofi users:
# kmenu "rofi -dmenu"
#
# for dmenu users:
# kmenu
#
# add it to your keyboard shortcut configs, and use kmenu!
#

menu=$1
test -z $1 && menu="dmenu"

# uncomment if you use this computer in public:
# main_menu=$(echo -e "continue" | $menu -p "careful: this will display your logins! select any to continue" -lines 0) || exit 1

test -z $kdatabase && {
	source $HOME/.config/k
}

kdbid=$(basename $kdatabase).kdb.$(echo $kdatabase | b2sum | cut -b1-8)

test -z "$(ls -A /tmp/"$kdbid")" && {
    xfce4-terminal --hide-menubar --hide-scrollbar -e "k open"
}

titles=$(k list_menu | awk -F $'\t' '{print $1}')
logins=$(k list_menu | awk -F $'\t' '{print $2}')

entry=$(k list_menu | awk -F $'\t' '{print $1" "$2}' | nl -s '. ' -w 1 | $menu | awk -F '.' '{print $1}')

test -z "$entry" && exit 1

entrytitle=$(echo "$titles" | sed -n ${entry}p)
login=$(echo "$logins" | sed -n ${entry}p)
password=$(k get "$entrytitle" | tail -n1)
totp=$(k totp "$entrytitle" | tail -n1)

choice=$(echo -e "password\nlogin+password\nlogin\ntotp\nlogin[pause]password" | $menu) || exit 1

enter_prompt() {
    continue=$(echo -e "press enter\ncancel" | rofi -dmenu)
    case "$continue" in
        "press enter") sleep 0.3; xdotool key Return;;
        "cancel") exit 1;;
    esac
}

type_string() {
    local str=$1
    for (( i=0; i<${#str}; i++ )); do
        char="${str:$i:1}"
        xdotool type "$char"
    done
}

case $choice in
    "login+password")
        type_string "$login"
        sleep 0.05
        xdotool key Tab
        sleep 0.05
        type_string "$password"
        enter_prompt
        ;;
    "login[pause]password")
        type_string "$login"
        sleep 0.05
        xdotool key Enter
        echo "wait until done and continue" | $menu || exit 1
        type_string "$password"
        enter_prompt
        ;;
    "password")
        type_string "$password"
        enter_prompt
        ;;
    "login")
        type_string "$login"
        ;;
    "totp")
        type_string "$totp"
        ;;
esac
